version: "3.7"
services:
  longvinter-server:
    container_name: longvinter-server
    image: longvinter-linux-server
    build: .
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "7777:7777/udp"
      - "27016:27016/tcp"
      - "27016:27016/udp"
    environment:
      CFG_SERVER_NAME: "MrRacoonCity"
      CFG_MAX_PLAYERS: "16"
      CFG_SERVER_MOTD: "Welcome to MrRacoonCity!"
      CFG_PASSWORD: "thereisnospoon"
      CFG_COMMUNITY_WEBSITE: "https://github.com/MrRacoon/longvinter-docker-server"
      CFG_ADMIN_STEAM_ID: "76561198041665835"
      CFG_ENABLE_PVP: "true"
      CFG_TENT_DECAY: "true"
      CFG_MAX_TENTS: "5"
      CFG_GAME_PORT: "7777"
      CFG_QUERY_PORT: "27016"
    volumes:
      - longvinter_data:/data
    restart: unless-stopped

volumes:
  longvinter_data:
    name: longvinter_data
